import QueryProvider from "@web/providers/QueryProvider";
import "./globals.css";
import Header from "./components/Header";
import { client } from "@web/utils/client";
import { headers } from "next/headers";
import { authClient } from "@web/utils/authClient";
import { SocketProvider } from "@web/providers/SocketProvider";
import { Toaster } from "@web/components/ui/toaster";
import { ThemeProvider } from "@web/providers/ThemeProvider";
import { VoiceProvider } from "@web/providers/VoiceProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await authClient.getSession({
    fetchOptions: {
      headers: await headers(),
    },
  });

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <QueryProvider>
          <SocketProvider session={session?.data}>
            <VoiceProvider session={session?.data}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children}
                <Toaster />
              </ThemeProvider>
            </VoiceProvider>
          </SocketProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
